import type { Ingredient, IngredientGroup } from "./types";

/**
 * DEMO ingredient library — descriptions are general, sensory and non-medical.
 * Traditional-use notes are cultural context, not health claims. Verify
 * botanical names and product associations with the founders before publishing.
 */
export const ingredients: Ingredient[] = [
  {
    slug: "neem",
    name: "Neem",
    botanicalName: "Azadirachta indica",
    group: "Botanicals & herbs",
    summary: "A time-honoured Indian botanical with a clean, green character.",
    why: "Long used across Indian households, neem lends our cleansing bars a fresh, purifying feel for everyday use.",
    properties: ["Traditionally valued", "Refreshing", "Green, herbaceous"],
    usedIn: ["Neem & Tulsi Soap"],
  },
  {
    slug: "tulsi",
    name: "Tulsi (Holy Basil)",
    botanicalName: "Ocimum tenuiflorum",
    group: "Botanicals & herbs",
    summary: "The familiar holy basil found in homes across India.",
    why: "Tulsi adds a bright, herbal note and a sense of everyday freshness to our formulations.",
    properties: ["Aromatic", "Familiar", "Uplifting scent"],
    usedIn: ["Neem & Tulsi Soap"],
  },
  {
    slug: "amla",
    name: "Amla (Indian Gooseberry)",
    botanicalName: "Phyllanthus emblica",
    group: "Botanicals & herbs",
    summary: "A classic hair-care botanical in Indian tradition.",
    why: "Amla is a staple of traditional hair care, chosen here to support a clean, cared-for feel.",
    properties: ["Traditional hair care", "Rich in character"],
    usedIn: ["Herbal Shampoo", "Herbal Hair Pack", "Hair Oil"],
  },
  {
    slug: "papaya",
    name: "Papaya",
    botanicalName: "Carica papaya",
    group: "Botanicals & herbs",
    summary: "A gentle fruit extract for a fresh daily cleanse.",
    why: "Papaya brings a soft, fruity character to a mild everyday cleansing bar.",
    properties: ["Gentle", "Fruity", "Everyday"],
    usedIn: ["Papaya Soap"],
  },
  {
    slug: "beetroot",
    name: "Beetroot",
    botanicalName: "Beta vulgaris",
    group: "Botanicals & herbs",
    summary: "A natural source of that warm, rosy tint.",
    why: "We use beetroot to colour a soap naturally, without synthetic dyes.",
    properties: ["Natural colour", "Plant-derived"],
    usedIn: ["Beetroot Soap"],
  },
  {
    slug: "shea-butter",
    name: "Shea Butter",
    botanicalName: "Vitellaria paradoxa",
    group: "Plant butters & oils",
    summary: "A rich, creamy butter that makes soap feel indulgent.",
    why: "Shea butter gives our bars a creamy lather and helps skin feel soft and comfortable after washing.",
    properties: ["Rich & creamy", "Softening", "Nourishing feel"],
    usedIn: ["Shea Butter Soap", "Triple Butter Soap", "Body Lotion", "Foot Cream", "Strawberry Lip Balm", "Goat Milk Soap"],
  },
  {
    slug: "cocoa-butter",
    name: "Cocoa Butter",
    botanicalName: "Theobroma cacao",
    group: "Plant butters & oils",
    summary: "A velvety butter with a naturally comforting note.",
    why: "Cocoa butter adds richness and a smooth, cared-for finish to our triple-butter bar.",
    properties: ["Velvety", "Comforting", "Conditioning feel"],
    usedIn: ["Triple Butter Soap"],
  },
  {
    slug: "mango-butter",
    name: "Mango Butter",
    botanicalName: "Mangifera indica",
    group: "Plant butters & oils",
    summary: "A light plant butter with a soft, cushiony feel.",
    why: "Mango butter rounds out our butter blend with a lighter, silky character.",
    properties: ["Light", "Silky", "Softening feel"],
    usedIn: ["Triple Butter Soap"],
  },
  {
    slug: "coconut-oil",
    name: "Coconut Oil",
    botanicalName: "Cocos nucifera",
    group: "Plant butters & oils",
    summary: "The everyday oil behind a good, bubbly lather.",
    why: "Coconut oil helps our soaps build a satisfying lather while keeping the base plant-derived.",
    properties: ["Lathering", "Plant-derived", "Everyday"],
    usedIn: ["Shea Butter Soap", "Neem & Tulsi Soap", "Papaya Soap", "Beetroot Soap", "Glycerine Soap", "Hair Oil", "Aloe Vera Soap", "Charcoal Soap", "Coffee Soap", "Goat Milk Soap", "Honey Soap", "Manjista Soap", "Red Wine Soap", "Sandal Soap"],
  },
  {
    slug: "glycerin",
    name: "Vegetable Glycerin",
    botanicalName: "Plant-derived glycerol",
    group: "Plant butters & oils",
    summary: "A humectant that helps skin feel comfortable, not tight.",
    why: "Glycerin draws in a little moisture, so our cleansers feel mild rather than stripping.",
    properties: ["Humectant", "Mild", "Comforting"],
    usedIn: ["Natural Dishwash Liquid", "Shea Butter Soap", "Papaya Soap", "Beetroot Soap", "Glycerine Soap", "Rose Face Wash", "Lavender Body Wash", "Body Lotion", "Face Cream", "Aloe Vera Soap", "Charcoal Soap", "Coffee Soap", "Manjista Soap", "Sandal Soap"],
  },
  {
    slug: "reetha",
    name: "Reetha (Soapnut)",
    botanicalName: "Sapindus mukorossi",
    group: "Natural cleansers",
    summary: "A naturally foaming fruit used for centuries to clean.",
    why: "Reetha is a traditional, plant-based cleanser we lean on for gentle, everyday washing.",
    properties: ["Naturally foaming", "Traditional cleanser", "Gentle"],
    usedIn: ["Natural Dishwash Bar", "Herbal Shampoo"],
  },
  {
    slug: "shikakai",
    name: "Shikakai",
    botanicalName: "Senegalia rikii",
    group: "Natural cleansers",
    summary: "The classic 'fruit for hair' of Indian tradition.",
    why: "Shikakai is a much-loved traditional hair cleanser, chosen for a mild, everyday clean.",
    properties: ["Traditional hair wash", "Mild", "Time-honoured"],
    usedIn: ["Herbal Shampoo", "Herbal Hair Pack"],
  },
  {
    slug: "lemon",
    name: "Lemon & Citrus",
    botanicalName: "Citrus limon",
    group: "Essential oils & extracts",
    summary: "A bright, fresh note that says 'clean'.",
    why: "Citrus lends a crisp, uplifting scent to our home-care range and cuts through everyday grease.",
    properties: ["Fresh & zesty", "Grease-cutting", "Uplifting"],
    usedIn: ["Natural Dishwash Liquid", "Natural Floor Cleaner"],
  },
  {
    slug: "lavender",
    name: "Lavender",
    botanicalName: "Lavandula angustifolia",
    group: "Essential oils & extracts",
    summary: "A calming floral that turns a wash into a wind-down.",
    why: "Lavender gives our body wash a soft, soothing scent for a calmer everyday routine.",
    properties: ["Calming scent", "Floral", "Soothing"],
    usedIn: ["Lavender Body Wash"],
  },
  {
    slug: "rose",
    name: "Rose",
    botanicalName: "Rosa",
    group: "Essential oils & extracts",
    summary: "A gentle floral for a fresh, delicate finish.",
    why: "Rose brings a light, pleasant fragrance to our facial cleanser without overpowering.",
    properties: ["Delicate", "Fresh floral", "Gentle"],
    usedIn: ["Rose Face Wash"],
  },
  {
    slug: "aloe-vera",
    name: "Aloe Vera",
    botanicalName: "Aloe barbadensis",
    group: "Essential oils & extracts",
    summary: "A soothing plant gel that keeps things gentle.",
    why: "Aloe adds a soft, soothing quality to our facial and body cleansers.",
    properties: ["Soothing", "Gentle", "Plant gel"],
    usedIn: ["Rose Face Wash", "Lavender Body Wash", "Body Lotion", "Face Cream", "Aloe Vera Gel", "Aloe Vera Soap"],
  },
  {
    slug: "hibiscus",
    name: "Hibiscus",
    botanicalName: "Hibiscus rosa-sinensis",
    group: "Botanicals & herbs",
    summary: "The bright red flower found in gardens across India.",
    why: "Hibiscus is a long-standing part of Indian hair care, and lends our hair pack its deep colour and soft, conditioned feel.",
    properties: ["Traditional hair care", "Rich natural colour", "Familiar garden flower"],
    usedIn: ["Herbal Hair Pack"],
  },
  {
    slug: "curry-leaf",
    name: "Curry Leaf",
    botanicalName: "Murraya koenigii",
    group: "Botanicals & herbs",
    summary: "The kitchen leaf that also has a place in hair care.",
    why: "Curry leaf is steeped into our hair oil, adding a warm, green, unmistakably South Indian character.",
    properties: ["Traditionally valued", "Warm, green note", "Everyday kitchen herb"],
    usedIn: ["Hair Oil"],
  },
  {
    slug: "sandalwood",
    name: "Sandalwood",
    botanicalName: "Santalum album",
    group: "Botanicals & herbs",
    summary: "A warm, woody classic of Indian bathing.",
    why: "Sandalwood gives our bar its familiar soft, woody scent — the smell many of us associate with a proper wash.",
    properties: ["Warm, woody scent", "Classic in Indian bathing", "Long-familiar"],
    usedIn: ["Sandal Soap"],
  },
  {
    slug: "manjistha",
    name: "Manjistha",
    botanicalName: "Rubia cordifolia",
    group: "Botanicals & herbs",
    summary: "A traditional root with a deep, earthy red tone.",
    why: "Manjistha root colours our bar naturally and carries a long history of traditional use in India.",
    properties: ["Traditional botanical", "Natural earthy colour", "Root-derived"],
    usedIn: ["Manjista Soap"],
  },
  {
    slug: "henna",
    name: "Henna",
    botanicalName: "Lawsonia inermis",
    group: "Botanicals & herbs",
    summary: "The leaf behind India's oldest natural hair colour.",
    why: "We sift henna finely so it mixes smoothly at home, with nothing added to it.",
    properties: ["Finely sifted", "Nothing added", "Traditional hair care"],
    usedIn: ["Henna Powder"],
  },
  {
    slug: "rosemary",
    name: "Rosemary",
    botanicalName: "Salvia rosmarinus",
    group: "Botanicals & herbs",
    summary: "A crisp, aromatic herb used as a scalp mist.",
    why: "Rosemary water gives our hair spray its clean, herbal lift for a mid-day refresh.",
    properties: ["Crisp herbal aroma", "Light and refreshing", "Everyday use"],
    usedIn: ["Rosemary Hair Spray"],
  },
  {
    slug: "coffee",
    name: "Coffee",
    botanicalName: "Coffea arabica",
    group: "Botanicals & herbs",
    summary: "Ground coffee, for a light scrub and a warm aroma.",
    why: "The grounds give our coffee bar a gentle texture and the roasted smell that wakes you up in the shower.",
    properties: ["Light natural scrub", "Warm roasted aroma", "Kitchen-familiar"],
    usedIn: ["Coffee Soap"],
  },
  {
    slug: "argan-oil",
    name: "Argan Oil",
    botanicalName: "Argania spinosa",
    group: "Plant butters & oils",
    summary: "A light oil that smooths without weighing hair down.",
    why: "A few drops of argan oil in our serum help hair look smooth and settled rather than greasy.",
    properties: ["Lightweight", "Smoothing finish", "Absorbs quickly"],
    usedIn: ["Hair Serum"],
  },
  {
    slug: "grape-seed-oil",
    name: "Grape & Grape Seed",
    botanicalName: "Vitis vinifera",
    group: "Plant butters & oils",
    summary: "A light oil and extract pressed from grapes.",
    why: "Grape seed oil keeps our red wine bar soft and light, and the grape extract gives it its deep berry tone.",
    properties: ["Light, non-heavy", "Deep natural colour", "Fruit-derived"],
    usedIn: ["Red Wine Soap"],
  },
  {
    slug: "peppermint",
    name: "Peppermint",
    botanicalName: "Mentha × piperita",
    group: "Essential oils & extracts",
    summary: "A cool, sharp oil for tired feet.",
    why: "Peppermint gives our foot cream its cooling finish at the end of a long day.",
    properties: ["Cooling sensation", "Sharp, clean scent", "A little goes far"],
    usedIn: ["Foot Cream"],
  },
  {
    slug: "strawberry",
    name: "Strawberry",
    botanicalName: "Fragaria × ananassa",
    group: "Essential oils & extracts",
    summary: "A soft fruit note for a lip balm.",
    why: "Strawberry gives our lip balm its gentle colour and the light fruity scent children ask for.",
    properties: ["Soft fruit scent", "Light natural tint", "Gentle"],
    usedIn: ["Strawberry Lip Balm"],
  },
  {
    slug: "activated-charcoal",
    name: "Activated Charcoal",
    group: "Clays & minerals",
    summary: "Fine black powder that gives our bar its marbling.",
    why: "Activated charcoal makes for a thorough, fresh-feeling wash and gives the bar its striking grey-black colour.",
    properties: ["Thorough cleanse", "Deep natural colour", "Finely milled"],
    usedIn: ["Charcoal Soap"],
  },
  {
    slug: "multani-mitti",
    name: "Multani Mitti (Fuller's Earth)",
    group: "Clays & minerals",
    summary: "The clay generations have used as a face pack.",
    why: "Multani mitti is the base of our face pack — it mixes into a smooth paste and rinses away cleanly.",
    properties: ["Traditional clay", "Smooth to mix", "Rinses clean"],
    usedIn: ["Face Pack"],
  },
  {
    slug: "honey",
    name: "Honey",
    group: "From the kitchen",
    summary: "A kitchen staple that softens a soap bar.",
    why: "Honey gives our bar its golden colour and a gentler, softer lather.",
    properties: ["Softer lather", "Warm natural colour", "Kitchen-familiar"],
    usedIn: ["Honey Soap"],
  },
  {
    slug: "oats",
    name: "Oats",
    botanicalName: "Avena sativa",
    group: "From the kitchen",
    summary: "Finely ground oats for a gentle texture.",
    why: "Ground oats give our honey bar a soft, mild texture rather than a harsh scrub.",
    properties: ["Very gentle texture", "Mild", "Everyday"],
    usedIn: ["Honey Soap"],
  },
  {
    slug: "goat-milk",
    name: "Goat Milk",
    group: "From the kitchen",
    summary: "Gives a soap its creamy, mild character.",
    why: "Goat milk makes for a notably creamy lather and a mild bar for everyday washing.",
    properties: ["Creamy lather", "Mild for daily use", "Traditional"],
    usedIn: ["Goat Milk Soap"],
  },
  {
    slug: "gram-flour",
    name: "Gram Flour (Besan)",
    group: "From the kitchen",
    summary: "Besan — the bath powder base used for generations.",
    why: "Gram flour is the base of our herbal bath powder, the way it has been prepared in Indian homes for years.",
    properties: ["Traditional ubtan base", "Fine texture", "Kitchen-familiar"],
    usedIn: ["Herbal Bath Powder"],
  },
  {
    slug: "beeswax",
    name: "Beeswax",
    group: "From the kitchen",
    summary: "What holds a lip balm together.",
    why: "Beeswax gives our lip balm its firmness so it stays put in a pocket rather than melting away.",
    properties: ["Holds its shape", "Protective film", "Natural wax"],
    usedIn: ["Strawberry Lip Balm"],
  },
];

/**
 * The families we ship with. The admin can add, rename and reorder families
 * from Studio — see lib/ingredient-store.ts `getIngredientGroups()` for the
 * live list. This constant is only the starting point.
 */
export const DEFAULT_INGREDIENT_GROUPS: IngredientGroup[] = [
  "Botanicals & herbs",
  "Plant butters & oils",
  "Natural cleansers",
  "Essential oils & extracts",
  "Clays & minerals",
  "From the kitchen",
];

export function getIngredientBySlug(slug: string): Ingredient | undefined {
  return ingredients.find((i) => i.slug === slug);
}

export function getIngredientsByGroup(group: IngredientGroup): Ingredient[] {
  return ingredients.filter((i) => i.group === group);
}
